### ISSUE TITLE
docker-compose up Django/DB Asset failure

### ISSUE THREAD

**Issue by mindfunk** [Patrowl/PatrowlManager#107]
I ran "docker-compose up" as per the installization instructions. It looks like the db setup is getting caught in an infinite loop. Not sure what to do here:

patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
patrowl-django |     return executor(sql, params, many, context)
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
patrowl-django |     return self.cursor.execute(sql, params)
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
patrowl-django |     raise dj_exc_value.with_traceback(traceback) from exc_value
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
patrowl-django |     return self.cursor.execute(sql, params)
patrowl-django | django.db.utils.ProgrammingError: relation "django_session" does not exist
patrowl-django | LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
patrowl-django |                                                              ^
patrowl-django |

**Comment by mindfunk** [comment]
getting this on when I hit the webpage:


Request Method: | GET
-- | --
http://web:8003/
2.2.10
ProgrammingError
relation "django_session" does not exist LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...                                                              ^
/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py in _execute, line 84
/opt/patrowl-manager/env3/bin/python
3.7.6
['/opt/patrowl-manager',  '/opt/patrowl-manager',  '/opt/patrowl-manager/env3/bin',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/opt/patrowl-manager/env3/lib/python3.7/site-packages']
Thu, 5 Mar 2020 22:37:21 +0100

**Comment by mindfunk** [comment]
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
patrowl-django |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
patrowl-django |     return executor(sql, params, many, context)
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
patrowl-django |     return self.cursor.execute(sql, params)
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
patrowl-django |     raise dj_exc_value.with_traceback(traceback) from exc_value
patrowl-django |   File "/opt/patrowl-manager/env3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
patrowl-django |     return self.cursor.execute(sql, params)
patrowl-django | django.db.utils.ProgrammingError: relation "django_session" does not exist
patrowl-django | LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
patrowl-django |                                                              ^
patrowl-django |

**Comment by MaKyOtOx** [comment]
Thanks ! (I've removed the buggy code)

**Comment by mindfunk** [comment]
I just ran a git pull and rebuilt from head. I'm still seeing the issue. Should I be using a branch and not master?

**Comment by sebastien-powl** [comment]
I'm on it :)
