### ISSUE TITLE
parse error in the settings.py.sample file

### ISSUE THREAD

**Issue by mindfunk** [Patrowl/PatrowlManager#110]
The following lines fail, if the environment variables are not set. The False is not a string, thus no lower() function. Also, some mention of settings.py in the installation instructions would be helpful. 

EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', False).lower() == 'true' # when port is 587
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', False).lower() == 'true' # when port is 465

perhaps should be:

EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False').lower() == 'true' # when port is 587
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true' # when port is 465

**Comment by sebastien-powl** [comment]
This issue should be fixed now, let met know (`commit ef56e68fa3234bad44f8815707f1c0cf49f7c6d`)
