### ISSUE TITLE
Commit 92ee703 broke default admin/passwd user creation

### ISSUE THREAD

**Issue by mindfunk** [Patrowl/PatrowlManager#111]
After you build, when you run "docker-compose up" you will get SQL parse errors and will not be able to login with the admin default credentials. 

This was broken with commit 92ee703 in the file docker-entrypoint.sh. The containers will build, but the SQL fails when running "docker-compose up".

**Comment by batebates** [comment]
Hello,
I got the same issue,
I replaced the following code in docker-entrypoint.sh l29
` echo "\

from django.contrib.auth import get_user_model; \
User = get_user_model(); \
User.objects.create_superuser('admin', 'admin@dev.patrowl.io', 'Bonjour1!') if User.objects.count() == 0 else pass" | python manage.py shell`

by `  echo -e "from django.contrib.auth import get_user_model\nUser = get_user_model()\nif User.objects.count()==0:\n\tUser.objects.create_superuser('admin', 'admin@dev.patrowl.io', 'Bonjour1!')" | python manage.py shell`

**Comment by sebastien-powl** [comment]
Hi, this issue was fixed in the last update (`commit d6b7603b339435b5cda43b31c28ef8231254d352`)
