### ISSUE TITLE
Update Manager

### ISSUE THREAD

**Issue by AntoninHL** [Patrowl/PatrowlManager#117]
Hi!

I installed a Patrowl server some time ago, and I wanted to make sure it was up to date. Both in terms of functionality and security.

How do I update the instance?

Thanks

**Comment by MaKyOtOx** [comment]
Hello @weSh !
If you installed Patrowl using Docker images: `docker pull` ;)
If you installed Patrowl using sources, try this (within Python virtualenv):
```
pip install -r requirements.txt
python manage.py makemigrations
python manage.py migrate
```
