### ISSUE TITLE
PDF ? and Raw ouput is not implemented

### ISSUE THREAD

**Issue by vletoux** [Patrowl/PatrowlManager#121]
The Raw output is not implemented.

While navigating in the /assets/details/ page, I found out the csv link is not present, but instead a PDF button is here, and not implemented

![image](https://user-images.githubusercontent.com/10632326/79834479-6ed11b00-83ad-11ea-9c28-852b092e99b7.png)

This test has been made with the nmap engine

**Comment by MaKyOtOx** [comment]
The links are now hidden until the feature correctly implemented
Thanks!
