### ISSUE TITLE
add new assets in bulk (CSV) does not Work

### ISSUE THREAD

**Issue by ichossef** [Patrowl/PatrowlManager#127]
Hello guys, 

I hope that you all are doing well.

I am having issues adding assets in bulk using a CSV file. I've used the template given in the Manager 
[assets_bulk.zip](https://github.com/Patrowl/PatrowlManager/files/4688161/assets_bulk.zip)

 and I receive a traceback error 
[KeyError at _assets_bulkadd.zip](https://github.com/Patrowl/PatrowlManager/files/4688176/KeyError.at._assets_bulkadd.zip)

Could you help me pls ?

Best regards,

**Comment by MaKyOtOx** [comment]
Hi,
Your CSV file seems to be buggy:
```
line | OrderedDict([('\ufeffasset_value', 'patrowl.io'),
 ('asset_name', 'Patrowl domain name'),
('asset_type', 'domain'), 
('asset_description', 'Patrowl domain name'), 
('asset_criticity', 'high'), 
 ('asset_groupname', 'recently_imported')])
-- | --
```
a Unicode char '\ufeff' has been added in the first line/cell

Could you please try to remove it ?

**Comment by agrandville** [comment]
hi @ichossef, your file was probably generated on Windows OS. Your file begins with 3 bytes EF BB BF corresponding to [UTF8-BOM](https://en.wikipedia.org/wiki/Byte_order_mark). Try to save your file without encoding eg. with notepad++ 
![image](https://user-images.githubusercontent.com/7641990/83327442-247c6d00-a27c-11ea-8591-083ab17614f8.png)
