### ISSUE TITLE
Patrowl VM won't send alerts

### ISSUE THREAD

**Issue by webhead404** [Patrowl/PatrowlManager#134]
The integration for Patrowl to The Hive doesn't work. Here is an example log:

[Rule][send_thehive_message()] Unable to send alert to TheHive with (error=Expecting value: line 1 column 1 (char 0), message ='[Asset=x.x.x.x] tcp/3128: Apache 2.4.x < 2.4.39 Multiple Vulnerabilities (4758a9)')

**Comment by MaKyOtOx** [comment]
Hello,
Could you please confirm you correctly add these settings ?
- alerts.endpoint.thehive.apikey
- alerts.endpoint.thehive.url
- alerts.endpoint.thehive.user

More information here: https://medium.com/@nicolas.mattiocco/anticipate-cyber-threats-with-patrowl-manage-them-with-thehive-e640394c23bc

**Comment by MaKyOtOx** [comment]
Great :)
