### ISSUE TITLE
Openvas & Arachni engines Failed

### ISSUE THREAD

**Issue by AntoninHL** [Patrowl/PatrowlManager#140]
Hi,

I installed Openvas & Arachni engines in my patrowl server.
Everything is configured well:
![image](https://user-images.githubusercontent.com/50768/85593281-2fda7280-b647-11ea-8318-90392c0e6239.png)

But when I try to start scan, I always have errors:

Openvas: `[EngineTasks/startscan_task/9139638a-addc-4874-87b9-d12d2997f978] DuringScan - something goes wrong (response_status_code=200, response_status=refused, response_details=scanner not ready). Task aborted.`

Arachni: `[EngineTasks/startscan_task/c17c254a-9370-4aff-9196-1bc9cdcf5f54] DuringScan - something goes wrong (response_status_code=200, response_status=ERROR, response_details=Unknown). Task aborted.`

Do you have an idea of the reason it doesn't work?
Nmap scan works fine.

Thanks for help.

A.

**Comment by AntoninHL** [comment]
It's really strange. Instable.
After many reboot, it works.... for few assets.
I tried to add more, launched scan... and error again. 
I stopped the openvas docker, and the openvas-engine docker... but no more success...

**Comment by AntoninHL** [comment]
Hi @MaKyOtOx 

You are right, it was a question of time... I have to wait about 15 minutes after launching Openvas docker.
But, now, I have another issue... :-(

Scan is launched in PatrOwl Manager and order is given to Openvas. I can see in Openvas that scans are defined and launched.
But, after few seconds in PatrOwl Manager, I have an error (not always, but often): "something's wrong during the scan"...
But scan is still running in Openvas and I have results!

**Comment by clouca** [comment]
same issue here. did you find a workaround ?
