### ISSUE TITLE
Error with last commit : Merge pull request #139 from agrandville/APIVoid

### ISSUE THREAD

**Issue by VOUGY** [Patrowl/PatrowlManager#141]
Hello @MaKyOtOx,

From the last update, it isn't possible to add new assets :
![AssetsAdd](https://user-images.githubusercontent.com/28144077/85919078-88d52100-b868-11ea-933d-ea08dcb732c0.png)

Do you have a idea to fix this problem ?

Thanks you

**Comment by agrandville** [comment]
@VOUGY i guess you forgot to update the models

Try this
```console
(env3) arnaud@agra....cloudapp.azure.com:/home/arnaud/PatrowlManager# ./manage.py makemigrations
Migrations for 'users':
  users/migrations/0002_auto_20200627_1318.py
    - Create model Team
    - Remove field bio from profile
    - Remove field department from profile
    - Create model TeamUser
    - Create model TeamOwner
    - Add field users to team
Migrations for 'assets':
  assets/migrations/0002_auto_20200627_1318.py
    - Add field teams to asset
    - Add field teams to assetgroup
    - Alter field owner on asset
Migrations for 'events':
  events/migrations/0004_auto_20200627_1318.py
    - Add field owner to alert
    - Add field teams to alert
Migrations for 'scans':
  scans/migrations/0002_scandefinition_teams.py
    - Add field teams to scandefinition
(env3) arnaud@agra....cloudapp.azure.com:/home/arnaud/PatrowlManager# ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, assets, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, 
engines, events, findings, rules, scans, sessions, settings, users
Running migrations:
  Applying users.0002_auto_20200627_1318... OK
  Applying assets.0002_auto_20200627_1318... OK
  Applying events.0004_auto_20200627_1318... OK
  Applying scans.0002_scandefinition_teams... OK
```
 some models have been updated recently

**Comment by VOUGY** [comment]
@agrandville thank you to your reply !

I thought that automatically when I run docker-compose build but all seem OK now

Thank you yet

**Comment by VOUGY** [comment]
@agrandville,  I'm sorry I believed it was ok but no ...

How do you update from docker-compose ? I tried to connect into the docker with docker exec and execute /docker-entrypoint.with-engines.sh but I have no migrations that applied : 
![image](https://user-images.githubusercontent.com/28144077/85923445-656f9d80-b88b-11ea-94e3-0f35dfad52fd.png)

My version is up-to-date : 1.4.0 
![image](https://user-images.githubusercontent.com/28144077/85923464-859f5c80-b88b-11ea-9d48-4d8c6cf0b074.png)


Thank you in advance for your reply
