### ISSUE TITLE
Periodical Scan Not Working

### ISSUE THREAD

**Issue by ozgursuder** [Patrowl/PatrowlManager#164]
Periodical scan stays without any operation for hours like below

![1](https://user-images.githubusercontent.com/16719254/87931712-e2f58a80-ca92-11ea-82fa-834d7206d365.JPG)
![2](https://user-images.githubusercontent.com/16719254/87931716-e426b780-ca92-11ea-9b75-cbb150adc8a9.JPG)

**Comment by ozgursuder** [comment]
![image](https://user-images.githubusercontent.com/16719254/87934209-48e41100-ca97-11ea-9781-3bf1bcfcef96.png)

**Comment by ozgursuder** [comment]
Periodic task does not work because asset information is not available

**Comment by MaKyOtOx** [comment]
Hello @ozgursuder: Do I have to understand you tried to start a scan without any asset ?

**Comment by ozgursuder** [comment]
Hi

I select periodical when doing a new scan.

it does the first scan without any problems, but when the periodic process comes up, as I sent it, there is no information in the asse section and no operation is possible.

**Comment by ozgursuder** [comment]
It works when I install the developer version before releasing the 1.5 version.

When I switched to version 1.5 it broke again.
