### ISSUE TITLE
Engines ERROR ( Nmap ,Arachni , OPENVAS ) Read timed out [PROXY]

### ISSUE THREAD

**Issue by CypFR** [Patrowl/PatrowlManager#165]
![Pb-engines](https://user-images.githubusercontent.com/68596751/88056408-c758b580-cb60-11ea-8585-3bf4f3f96adb.png)

Cannot add any engines on my Patrowl.

Reason : Reason: ReadTimeout thrown HTTPConnectionPool(host='xxxxxxxxx', port=8080): Read timed out. (read timeout=20)

Someone can help me to solve my issue ?

Thanks

**Comment by MaKyOtOx** [comment]
Hi @CypFR : Do you use the Docker image or native python installation ?

**Comment by CypFR** [comment]
I'm using Docker image!

 I added proxy address in my Dockerfile

**Comment by MaKyOtOx** [comment]
It's a common issuewhen using Docker images when deploying PatrowlManager and PatrowlEngines in separate contexts / stacks. Could you please double check the django-web container is able to interact (ping ?) the engines ?

**Comment by CypFR** [comment]
Sorry , but how can i check that ?

**Comment by MaKyOtOx** [comment]
You can open a bash session within the docker container (`docker exec -it <container_id> bash`) for example.

Btw, if you want, you can also use the all-in-one docker-compose for a quick try:
`docker-compose -f docker-compose.with-engines.sh up`

**Comment by CypFR** [comment]
My docker image is patrowl-django/

I succeed to open a bash session with container ID.



![Docker-exac-patrowl](https://user-images.githubusercontent.com/68596751/88063441-528a7900-cb6a-11ea-934d-f0da38e9bafb.png)
