### ISSUE TITLE
Disabling Debug breaks static content

### ISSUE THREAD

**Issue by znb** [Patrowl/PatrowlManager#17]
Bit of a strange one. I must be doing something wrong.

In my app/settings.py file if I have "DEBUG = True" everything works as it should. 
However, when I set it to "False", all the static content breaks with a 404 error.

Not sure what's wrong, but I suspect it's something simple I've overlooked. I've reviewed the documentation but can't find anything.

**Comment by MaKyOtOx** [comment]
Hi,
As a matter of fact, the Production mode (Debug=False) requires management of static files and fixing security options. Default security options (CSRF tokens, HSTS, flags set on session cookies, ...) have been just commited. 
We need to investigate for management of static files using `gunicorn/Nginx` stacks

**Comment by MaKyOtOx** [comment]
Fixed in commit https://github.com/Patrowl/PatrowlManager/commit/981385534d4d86fa8f0bdf34086f02404b901fa1
