### ISSUE TITLE
docker-compose up failes if ipv6 is disabled

### ISSUE THREAD

**Issue by fibaxx** [Patrowl/PatrowlManager#207]
I have tried to install Patrowl on Ubuntu 20.04. server. The server has ipv6 disabled via grub. If i use the command `docker-compose -f docker-compose.with-engines.yml up` i get the following error message:

ERROR: for patrowl-nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint patrowl-nginx (4a6ec3dbffea27950cc381aaf08e0dcc298727606aa81bd40333ff69bc3a0315): Error starting userland proxy: listen tcp6 [::]:8083: socket: address family not supported by protocol

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint patrowl-nginx (4a6ec3dbffea27950cc381aaf08e0dcc298727606aa81bd40333ff69bc3a0315): Error starting userland proxy: listen tcp6 [::]:8083: socket: address family not supported by protocol
ERROR: Encountered errors while bringing up the project.

The nginx_docker.conf file is untouched by me and has only the "listen 8083;" for ipv4 in it.

**Comment by MaKyOtOx** [comment]
Hi @fibaxx, Thank you for reporting this.
It seems to be related to Docker and Nginx configuration. Do you have an IPv4 / interface up on your system ?

**Comment by fibaxx** [comment]
Hi @MaKyOtOx,

yes, there is an IPv4 interface up on the system and i can connect to the server via ssh.

**Comment by fibaxx** [comment]
Hi @MaKyOtOx,

just want to let you know that this is not a PatrowlManager related issue.
After i updated packages on another docker server i had the same error message and no containers are getting started.
Docker itself has done something wrong. Until they fix it i reenabled IPv6 and it works. Thank you.
