### ISSUE TITLE
Change my password issue

### ISSUE THREAD

**Issue by zebux** [Patrowl/PatrowlManager#221]
Hello,
I don't know if I am the only one to have this issue,or if I loose somethink,  but after a fresh docker deployement  (docker-compose -f docker-compose.with-engines.yml up) with the community edition 1.6.26. I can login with admin and default password, but I can't change the admin password. When I click on "change my password" I return to the dashboard page.

In the browser dev tools, I can see I have on the page http://@IP:8083/users/editpw - 302 redirect to :  http://@IP/dashboard.

Best regards

**Comment by MaKyOtOx** [comment]
The 'admin' account is a little bit special for now. Password management could be done directly in the Django administration console: `/admin/auth/user/1/password/`
Could you please try it ?

**Comment by zebux** [comment]
Hello sorry for the delay, thanks for the reply... I will chack soon.
Bets regards and thanks a lot
