### ISSUE TITLE
Four instead of three criticality levels for assets

### ISSUE THREAD

**Issue by JasperJuergensen** [Patrowl/PatrowlManager#23]
In my opinion it would be better, if the assets are ranked in four criticality levels instead of three. If there are three criticality levels, many people will choose the one in the middle. With four, they are forced to give it at least a tendency.

**Comment by MaKyOtOx** [comment]
Hi Jasper, I understand your opinion and it's a recurring debate in risk assessment. We've selected the NIST 800-30 as the applicable standard (See https://www.hhs.gov/sites/default/files/ocr/privacy/hipaa/administrative/securityrule/nist800-30.pdf) and it define 3 levels of likelihood (finding level) and 3 levels of impact (asset criticity).

At the end of the day, it is not a big deal. Plus, if we had another asset criticality level, we have to change all summaries, bars, dashboard graphs and score/grade evaluation (lazy arguing ;)).

**Comment by MaKyOtOx** [comment]
Can I close this issue ?

**Comment by JasperJuergensen** [comment]
Yes, I think you can close this issue.
