### ISSUE TITLE
having Error code: SSL_ERROR_RX_RECORD_TOO_LONG 

### ISSUE THREAD

**Issue by tbaror** [Patrowl/PatrowlManager#231]
Hello ,

Suddenly having following issue shown below, when trying to get into Patrowl portal , looking on all containers  logs   nothing to indicate 
issue.
Please advice
Thanks
````
Secure Connection Failed

An error occurred during a connection to x.x.x.x:8083. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG`

```

**Comment by MaKyOtOx** [comment]
Hi @tbaror 
The docker images are not configured to support SSL/TLS by default.
Could you please double-check your custom nginx SSL configuration ? Or try to access x.x.x.x:8083 with 'http' instead of 'https'
Keep us posted :)

**Comment by tbaror** [comment]
> Hi @tbaror The docker images are not configured to support SSL/TLS by default. Could you please double-check your custom nginx SSL configuration ? Or try to access x.x.x.x:8083 with 'http' instead of 'https' Keep us posted :)

You are right , my bad , i was convinced its https , works for http
Thank you
