### ISSUE TITLE
'Select Engine' dropdown shows up empty

### ISSUE THREAD

**Issue by jgonzalez-csirtrd** [Patrowl/PatrowlManager#241]
Hi,

I'm trying to add a new scan definition, only to find the engine dropdown empty.

![Screenshot 2022-01-12 152550](https://user-images.githubusercontent.com/92810781/149208427-8fcf40de-e65f-4afb-a4b3-6269f4d38bfd.png)

And it seems all my engines are up and running correctly.

![Screenshot 2022-01-12 152659](https://user-images.githubusercontent.com/92810781/149208454-00fd3f02-fa45-4ba9-b9d5-d6b4d295f4dd.png)

**Comment by gdanldo** [comment]
+1 for follow
Same things and impossible to add openvas :( 
Tried old versions and old tutorials finded on google and can't configure anything.
If anyone have an updated tutorial to use Patrowl with openvas and aracni with TheHive :)

**Comment by MaKyOtOx** [comment]
Hi all, Thank for the issue and the PR #240 
All will be fixed in the next release 1.8.0 as the end of week

**Comment by MaKyOtOx** [comment]
This should be fixed in version 1.8.0
