### ISSUE TITLE
Finding import: asset value can only be ip

### ISSUE THREAD

**Issue by JasperJuergensen** [Patrowl/PatrowlManager#25]
When you import findings (with new assets) the asset value can only be an ip address. This causes issues with multiple systems/domains behind a one ip address. Then only one asset will be created and the findings (for multiple systems/domains) will be added to this one asset. 

Proposed solution: Change the format for the `_import_findings` and the `_create_asset_on_import` method, so that assets are not only a list but a dict with the asset parameters.

```json
{
    "targets": [
        {
            "name": "System name",
            "type": "fqdn/ip/rdns/...",
            "value": "system.example.com/1.2.3.4/...",
            "description": "infos",
            "categroies": ["OS", "Windows Server"]
        }
    ],
    "metadata": {
        "risk": {
            "cvss_base_score": "0.0"
        },
        "vuln_refs": {},
        "links": [],
        "tags": []
    },
    "title": "title",
    "type": "Vuln",
    "confidence": "3",
    "severity": "info",
    "description": "n/a",
    "solution": "n/a",
    "raw": ""
}
```

**Comment by MaKyOtOx** [comment]
Fixed with PR https://github.com/Patrowl/PatrowlManager/pull/27
