### ISSUE TITLE
New Scan Definition

### ISSUE THREAD

**Issue by psantos1** [Patrowl/PatrowlManager#34]
Hi,

I am trying to configure a new scan. However, the search for an asset doesn't seem to be working, because when I insert some text, nothing occurs. 
Example
    
  I have an asset named google, and the I try to configure a scan this is what I am seeing: 

![captura de ecra 2018-12-11 as 09 43 14](https://user-images.githubusercontent.com/44494343/49791984-87491400-fd29-11e8-94ca-62c6b1066451.png)

Regards

**Comment by MaKyOtOx** [comment]
Hi !
1/ For the moment, the search is only performed on the asset 'value' (and not the 'name' or 'description' fields). 
2/ The search is based on a Javascript function. So, could you please ensure that all Javascript files (static files) are available ?

Try this way and please tell us if it works :) Improvements would be useful in the search feature.

**Comment by psantos1** [comment]
Hi!

You're correct, the client-side was not loading the js files, the problem was that the files contained under the static directory were expecting a directory named admin, which does not exist.

Thanks

**Comment by psantos1** [comment]
Hi @MaKyOtOx, any update on this matter?

**Comment by MaKyOtOx** [comment]
Hi,
It's now possible to search assets on their names or value. Regarding the missing JS files, could you please try to use the following command: 
`python manage.py collectstatic`

Thks for your feedbacks !

**Comment by psantos1** [comment]
Hi @MaKyOtOx ,

I believe you're were right about the JS files.
I reinstalled PatrowlManager and everything works fine now!

Thanks

**Comment by MaKyOtOx** [comment]
Nice :) Thank you ! I can close the issue now.
