### ISSUE TITLE
nginx service error in docker compose

### ISSUE THREAD

**Issue by pichlou** [Patrowl/PatrowlManager#36]
Hi 
i am using docker-compose in windows 7
postgres,rabbitmq and django application services build,but nginx service has an error!
 
nginx:
   volumes:
       - ./nginx_docker.conf:/etc/nginx/conf.d/default.conf

in this part "nginx_docker.conf" is not a directory and i have error "not a directory" in running "docker-compose up" command.
what is your solution for my problem?

**Comment by MaKyOtOx** [comment]
Hi Farzaneh,
I've never tested it on Windows OS :/. Maybe you should try to:
1/ Enable path conversion from Windows-style to Unix-style in volume definitions:`set COMPOSE_CONVERT_WINDOWS_PATHS=1`, and if it is not sufficient:
2/ Set the full path to the * nginx_docker.conf* file. Something like: `
nginx:
    volumes:
        - D:/my/path/to/nginx_docker.conf:/etc/nginx/conf.d/default.conf
`
