### ISSUE TITLE
Connect PatrowlManager with PatrowlEngine-VirusTotal

### ISSUE THREAD

**Issue by psantos1** [Patrowl/PatrowlManager#37]
Hi,

I've deployed a PatrowlEngine-VirusTotal running on port 5007 on the same machine as PatrowlManager which is running on port 8000. But I don't understand how am I supposed to connect the two.
From the "+ Add scan engine instance" view, it almost seems that it would create a new instance of the VirusTotal Engine instead of using the one already created. Does PatrowlManager recognizes the engine automatically?

Many thanks

**Comment by MaKyOtOx** [comment]
Hi,
You can create as many instances of each engine type (VT, NMAP, NESSUS, ...) as you like. You can also create multiple engine instance (different name) pointing to the same PatrowlEngine application (same API endpoint). In that case PatrowlManager is silly and does not recognize the engine type or if the engine instance is already set.
Do you think we have to change that ? or at least advise the user that the engine was already used ?

**Comment by psantos1** [comment]
Hi @MaKyOtOx,
Regarding your question I think its depends, I'm assuming that for example if the same VirusTotal PatrowlEngine application has multiple engine instances in PatrowlManager, it would go (by default) to a maximum of 25 simultaneous scans, according to the Virus-total PatrowlEngine application configuration right? In this case maybe you could alert the user.

However, my question is other. I'm having a difficult time connecting a VirusTotal PatrowlEngine application to my PatrowlManager, where can I see what is going wrong?
I can access the VirusTotal PatrowlEngine application API links and it seems to be working fine, but PatrowlManager seems incapable of recognizing it.
Thanks
