### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by dmwoods38** [Patrowl/PatrowlManager#39]
I was just wondering if there are any plans for moving the project to Python3 with the Python2 EOL coming up.

Thank you!

**Comment by MaKyOtOx** [comment]
Hello,
Yes, we definitely would like to upgrade to Python 3 and Django 2.x. For the moment, we are waiting for the Django 2.2 LTS version (should be released in april 2019).

**Comment by dmwoods38** [comment]
Thank you so much!

**Comment by MaKyOtOx** [comment]
Done :)
