### ISSUE TITLE
Engine type

### ISSUE THREAD

**Issue by Yradio** [Patrowl/PatrowlManager#46]
Hello,

I do not understand the impact to change the prebuilt allowed asset for each engine.
Do the code need a modification ? 

By default :
 - nmap is limited to only IP ? Adding fqdn and domain would be great.
- Why Nessus and nmap do not have ip-subnet vs openvas ?
 - Why Organization is never used. Could it be used for owl_leaks ?

**Comment by MaKyOtOx** [comment]
Hi,
I definitely agree that prebuilt allowed asset are missing for NMAP and NESSUS. It will be updated in the `var/data/engines.Engine.json` file.
The Organization is not yet used but as you mentioned, it could be used in owl_leaks use cases. By the way, this engine code and configuration have to be slightly updated.
