### ISSUE TITLE
Scan issues

### ISSUE THREAD

**Issue by cece46** [Patrowl/PatrowlManager#56]
i have this error (ssllab test)
![image](https://user-images.githubusercontent.com/32593390/58995815-01001d00-87f6-11e9-85f1-fc4bdadf39c4.png)

engine : 
![image](https://user-images.githubusercontent.com/32593390/58995848-18d7a100-87f6-11e9-8295-64a44783b592.png)

**Comment by nbeguier** [comment]
Can you give us the error log of the engine ? Is it up to date ?

**Comment by MaKyOtOx** [comment]
up !
