### ISSUE TITLE
Error add asset

### ISSUE THREAD

**Issue by cece46** [Patrowl/PatrowlManager#57]
![image](https://user-images.githubusercontent.com/32593390/58995964-8aafea80-87f6-11e9-957e-b35d057815ef.png)

**Comment by nbeguier** [comment]
Don't you have clicked twice ? It appends sometimes.
Does your asset is created ?

**Comment by jtabet010** [comment]
Hello, this is happeneing to me 2 , I get the error, but the asset is created

**Comment by jgrossemy** [comment]
I have this error too on new fresh install.
I'm sure I didn't click twice.
