### ISSUE TITLE
User has no profile

### ISSUE THREAD

**Issue by niening** [Patrowl/PatrowlManager#59]
Hi
I have a error when i first entre the site: localhost:8083, it's monitor the page and show 'user has no profile' after i enter the compte defaut(Admin/Bonjour1!)

Bien Cordialement
Merci
<img width="612" alt="patrowl-problem" src="https://user-images.githubusercontent.com/16206667/59692210-bd89b380-91e4-11e9-9eea-ba084faa13be.PNG">

**Comment by MaKyOtOx** [comment]
Hi, could you please use the last version and tryc again please ?
Thx !
