### ISSUE TITLE
how to use openvas ? (no default policy)

### ISSUE THREAD

**Issue by aderumier** [Patrowl/PatrowlManager#66]
Hi,
I'm trying to launch a scan with openvas, but currently no policy is available.

I have tried to add a policy manually (but I don't known what I need to fill in the options form),
and I'm getting an error

https://gist.github.com/aderumier/db85a0fea2e1ea1e3089fd068613e992.

Can somebody have some infos or tuto about openvas integration ?

**Comment by MaKyOtOx** [comment]
Hi,
You can use the following default policy:
```
{"profile": "Default", "port_list": "patrowl-tcp_443"}
```

Btw, we assume we have to create a full tutorial for openvas usage ! Many configurations are available, depending on your current openvas deployment

**Comment by MaKyOtOx** [comment]
Default OpenVAS policies are now loaded by default
