### ISSUE TITLE
Assets not saved in scan

### ISSUE THREAD

**Issue by rreilly-edr** [Patrowl/PatrowlManager#68]
Hi I am create a sslscan scan, I fill out the info search for my asset click update scan and the asset disappears.

here I add the asset 
[https://pasteboard.co/In5fWqk.png](https://pasteboard.co/In5fWqk.png)

and update and it is gone
[https://pasteboard.co/In5fi2P.png](https://pasteboard.co/In5fi2P.png)

Version 1.1.1-RC3

**Comment by MaKyOtOx** [comment]
Hi !
Di you tried to press the Enter key or click on it when your asset is selected ?

**Comment by rreilly-edr** [comment]
Enter key, does that work ?

**Comment by rreilly-edr** [comment]
actually neither works for me

**Comment by rreilly-edr** [comment]
So I cleaned up the environment with docker-compose down, cleaned up the database files to start from new now I get the following error
`DateTimeShortcuts.js:12 Uncaught ReferenceError: gettext_noop is not defined
    at DateTimeShortcuts.js:12
    at DateTimeShortcuts.js:423`
