### ISSUE TITLE
Error Rules Route /add

### ISSUE THREAD

**Issue by ST2Labs** [Patrowl/PatrowlManager#7]
Hi, 

When try to add new Rules from "Nav-Menu" get a erros, because the "route" in urls.py it's not correct.

[Screenshots]
![image](https://user-images.githubusercontent.com/9781565/42637955-b2113bcc-85ec-11e8-90e9-02e662830ae8.png)

Need to change /rules/add to /rules/api/vi/add

Thanks!

**Comment by MaKyOtOx** [comment]
Hi,
Yes you're right. There is no form page for adding rules yet. The rules can be added at `/rules/list` only for the moment:
![capture d ecran 2018-07-13 a 10 30 21](https://user-images.githubusercontent.com/1262702/42681391-d3d9a898-8687-11e8-98f7-a96db22ff396.png)

Several UI/UX improvements are needed on rules management. A quick&dirty fix should be the removing of the Nav-Menu link
