### ISSUE TITLE
Scheduled scans - not working

### ISSUE THREAD

**Issue by dreadangel** [Patrowl/PatrowlManager#73]
Hi,

I intend to create a scheduled scan to be launched each day at 8am:
![image](https://user-images.githubusercontent.com/1151809/61266865-66a0db00-a79e-11e9-97bd-4b20991fa352.png)
But the scan didn't launch, moreover, on an attempt to edit it to be launched next day - the app fails:
![image](https://user-images.githubusercontent.com/1151809/61267014-c8614500-a79e-11e9-93ae-662ac357f8c2.png)
Also I've noticed that Scan Type is not saved:
![image](https://user-images.githubusercontent.com/1151809/61267118-2db53600-a79f-11e9-8b41-f9488b2dcb2b.png)

Any suggestion?

**Comment by MaKyOtOx** [comment]
Hi, Thank you for the issues. I've reviewed the code and the 2 following user stories are not implemented yet (my bad):
- Scheduled and periodic scan
- Restore scan type on scan editing

Btw, I suggest you to update the PatrowlManager version (and use Python 3 ;) ;) ;))

**Comment by dreadangel** [comment]
I've combined scan's scheduling with [ndscheduler](https://github.com/Nextdoor/ndscheduler) - [here](https://pastebin.com/iRN7qkpz) lies my job implementation
