### ISSUE TITLE
Error / Add New Scan | kombu.exceptions.OperationalError

### ISSUE THREAD

**Issue by ST2Labs** [Patrowl/PatrowlManager#8]
Hi, 

When I create new Scan (Sometimes) not always before run scan, raise Kombu Exceptions... 

![image](https://user-images.githubusercontent.com/9781565/42689809-35d72e34-86a2-11e8-899a-3e2b7348a8a8.png)

But New Scan have been create, but no started

Thanks

**Comment by MaKyOtOx** [comment]
not cool :/
- Would it be possible to have the full screen of the error stacktrace ? (or the bottom?)
- Do you use proxies ?
- Could you please confirm the versions of the following python modules (see `pip freeze`): kombu, celery, amqp

thx !

**Comment by ST2Labs** [comment]
Hi, @MaKyOtOx 


1. I will try to reproduce the error again and catch full screen !
2. No using proxy / only docker NAT (because I'm using docker swarm node to deploy)

## pip freeze

```
amqp==2.2.2
Babel==2.4.0
backports-abc==0.5
billiard==3.5.0.3
celery==4.0.2
certifi==2017.4.17
chardet==3.0.4
Django==1.11.10
django-celery-beat==1.0.1
django-celery-results==1.0.1
django-datetime-widget==0.9.3
django-debug-toolbar==1.8
django-extensions==1.8.1
djangorestframework==3.7.7
flower==0.9.2
future==0.16.0
futures==3.1.1
idna==2.5
jsonfield==2.0.2
kombu==4.1.0
libmagic==1.0
meld3==1.0.2
psycopg2-binary==2.7.5
python-magic==0.4.15
python-memcached==1.59
pytz==2018.3
requests==2.18.1
singledispatch==3.4.0.3
six==1.10.0
sqlparse==0.2.3
supervisor==3.3.2
thehive4py==1.4.3
tornado==4.5.1
urllib3==1.21.1
vine==1.1.4
virtualenv==16.0.0
Werkzeug==0.12.2
```

---

I think the root of error it "resource", i'm using docker over 1 node with only 5GB/RAM with 3 Engine & Manager.

Now I asign 6192 MB/RAM to docker engine, and I haven't this exception yet!

Thanks in advance

**Comment by A888R** [comment]
Hello!
I also get this error.
After F5:
![image](https://user-images.githubusercontent.com/8194134/42726431-0a7cc310-879d-11e8-975e-cbb698d5e7cb.png)
(double created)

**Comment by MaKyOtOx** [comment]
Thk for the stacktrace. I've reproduced the first bug with a full fresh install. 
I've updated the management of the timezone when the task is sent to Celery. I'm not able to reproduce the issue now, but I'm still testing the changes.

**Comment by MaKyOtOx** [comment]
It seems to be linked with a know Celery issue (https://github.com/celery/celery/issues/3377). I've added a recommended fix preventing the MQ broker going crazy:
In `app/settings.py`:
```
BROKER_POOL_LIMIT = None
```
