### ISSUE TITLE
Logout broken

### ISSUE THREAD

**Issue by nbeguier** [Patrowl/PatrowlManager#80]
Since Django 2.1, `contrib.auth.views.logout()` is deprecated and `django.contrib.auth.views.auth_logout()` isn't working with a `next_page` argument : https://docs.djangoproject.com/en/2.1/internals/deprecation/

```
logout() got an unexpected keyword argument 'next_page'
```

The idea is to migrate the authentication following this documentation : https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/

```
    path('accounts/', include('django.contrib.auth.urls')), # new
```
Something like this... but it's way more complicated :smile:

**Comment by MaKyOtOx** [comment]
Nice :)
