### ISSUE TITLE
Manual import for nessus xml reports does not work in latest version

### ISSUE THREAD

**Issue by dreadangel** [Patrowl/PatrowlManager#81]
Hi,

On Monday, August 19th, I've set up the environment through docker_compose file - all went good. 
The problem appeared when I attempted to manual import a Nessus xml report file - the app showed no error, but no findings were uploaded to the DB. Listing the `events` table revealed that only the first event were logged:
 `[EngineTasks/importfindings_task/5d3554af-1041-45f4-aa04-683603b2a3aa] Task started with engine nessus.`
after that - nothing, even exception. The docker also shows no exception.

I've added additional event recording to be sure that no exception occurs - below the `if engine == 'nessus':` and below the `else` - no event is recorded. I've wrapped the whole `importfindings_task` method content in a try/catch - again nothing!

Any suggestion?

P/S: Tested against latest version (at 2019.08.22) - same issue. Tested with latest version for Python 2 - seems fine

**Comment by MaKyOtOx** [comment]
Hi, Thank you for the issue. We have to work on this cause the format of XML nessus report might have changed.

**Comment by MaKyOtOx** [comment]
A bug was introduced in the python2/3 upgrade in the file `engines/tasks.py`:

```L110:    value_to_level = {v: k for k, v in level_to_value.iteritems()}```
To:
```L110:    value_to_level = {v: k for k, v in level_to_value.items()}```
