### ISSUE TITLE
importing gstatic fonts in bootstrap.min.css for non internet client blocks Manager access (until timeout)

### ISSUE THREAD

**Issue by marcas1** [Patrowl/PatrowlManager#83]
I got long borring waiting time for logging, accessing the manager. 
Until I figured it was a timeout ont css font file with Devtools in Firefox.

So I propose (as it a been done with glyphicons (but may be relative path would be better, I just see that)
1. Correct local bootstramin.css
in static/css/bootstrap.min.css first line should be changed
from `url("https://fonts.googleapis.com/css?family=Lato:400,700,400italic")`
to `url("/static/css/family-Lato.css");`

2. Get family-Lato font css and correct
  * wget -vv  https://fonts.googleapis.com/css?family=Lato:400,700,400italic -O -  |sed 's_https://fonts.gstatic.com/s/lato/v16/_/static/fonts/_' > static/css/family-Lato.css

3. get ttf files from 
  * https://fonts.gstatic.com/s/lato/v16/S6u8w4BMUTPHjxsAXC-v.ttf  https://fonts.gstatic.com/s/lato/v16/S6uyw4BMUTPHjx4wWw.ttf https://fonts.gstatic.com/s/lato/v16/S6u9w4BMUTPHh6UVSwiPHA.ttf
  * to  :
  * `static/fonts/S6u8w4BMUTPHjxsAXC-v.ttf  `,  `static/fonts/S6u9w4BMUTPHh6UVSwiPHA.ttf  `, `static/fonts/S6uyw4BMUTPHjx4wWw.ttf`

regards
MH

**Comment by MaKyOtOx** [comment]
Well done !! Thank you for the contribution :)
