### ISSUE TITLE
Edit scan impossible

### ISSUE THREAD

**Issue by nbeguier** [Patrowl/PatrowlManager#85]
I've discovered that editing a scan was not possible because the attribute "scan_type" is not sent to the api.

The mitigation is to click on the radio button to trigger the javascript which puts a `"clicked=True"` attribute.
This will add the fields and set the `form.is_valid()` to True, instead of unknown or False.

This is strange, because the default value seems to be "single", but I don't know why it's replaced by None...

**Comment by MaKyOtOx** [comment]
Fixed (the scan_type was never sent to the Manager). Btw we identified other issues when editing the scan definition
