### ISSUE TITLE
Problem with graphical interface in testing mode

### ISSUE THREAD

**Issue by manuelsantander** [Patrowl/PatrowlManager#87]
Good night. I just performed the installation under ubuntu 18.04 server. It is a virtual machine under VMWare Fusion. I was able to enter with the superuser created in accordance with the installation manual. However, no graphical interface of the application is shown and I can only see a broken interface in text mode in the browser. I am using python3. What could have happened?

**Comment by MaKyOtOx** [comment]
Hi Manuel,
It seems the static files are not served. You might tried to start the application in the Production mode (DEBUG=False) without using a front web server (Nginx ?).
A quick workaround could be to restart the Django application in the development mode: set the variable `DEBUG=True` in `app/settings.py`

**Comment by manuelsantander** [comment]
Thank you @MaKyOtOx for the info. I was able to correctly access the application with full graphical interface. This was done placing the DEBUG=true in the settings.py file. However, when I start Nginx and change back the DEBUG flag to false I keep getting the broken interface in text mode. The Nginx configuration file in the repository cannot be started with Nginx 1.14.0 as it gives several errors with plugins and server directive. I change the file and now looks like this:

events {
	worker_connections 4096;
}

http {
	server {
    		listen 80;
    		server_name my.patrowl.io;

		root .;
    		autoindex on;

    		access_log var/log/nginx.patrowlmanager-access.log;
    		error_log var/log/nginx.patrowlmanager-error.log;

    		location / {
			proxy_pass http://127.0.0.1:8003;
    		}

		location /static {
			alias ./staticfiles;
    		}
    		location /media {
        		alias ./media;
    		}
	}
}

Any ideas?

**Comment by MaKyOtOx** [comment]
The `nginx.conf` file provided in this repo is not a "full nginx configuration file". You just have to add this file in the directory /etc/nginx/conf.d/ (Ubuntu) and restart/reload your Nginx service.
Could you try again this way ?
