### ISSUE TITLE
Admin user does not exist

### ISSUE THREAD

**Issue by jgrossemy** [Patrowl/PatrowlManager#91]
When doing a new docker installation in version 1.1.2RC1 the login / password Admin / Bonjour1! does not work.
The user base is empty.

![image](https://user-images.githubusercontent.com/6997296/67699812-092b4580-f9ad-11e9-9537-785fc1e70656.png)

**Comment by MaKyOtOx** [comment]
Hi, Thank you for the bug report. 
We have reproduced the issue and a bug has been spotted in the `docker-entrypoint.sh file` (bad existence check on the file status.created).
`if [ -f status.created ]; then` --> `if [ ! -f status.created ]; then`
A patch will be soon released !
