### ISSUE TITLE
Docker install of branch master not working?

### ISSUE THREAD

**Issue by Owenmor** [Patrowl/PatrowlManager#95]
![image](https://user-images.githubusercontent.com/898217/68753948-baf98180-05fd-11ea-998f-794bf84493ad.png)

and in the browser I get:
![image](https://user-images.githubusercontent.com/898217/68754101-057afe00-05fe-11ea-9724-865c5f0fb5e4.png)

Should I try a different branch?

**Comment by MaKyOtOx** [comment]
huh, which version are you using ? Have you change anything in the nginx.conf or docker-compose files ?
