### ISSUE TITLE
Asset value max_length too small

### ISSUE THREAD

**Issue by david1davids** [Patrowl/PatrowlManager#96]
I wanted to create an asset with more ip-ranges. For example, I wanted to create an asset for with all the subnets from one location, this way the length of 256 characters is too low. The length should be increased to at least 2048.

**Comment by MaKyOtOx** [comment]
We can increase the length of the 'value' field. By the way, in your use case, you should create one asset for each ip-range and then create an asset group of these ip-range.

**Comment by david1davids** [comment]
Good point, this is what I will do.
